[16.0][MIG] repair_reinvoice: Migration to 16.0
OCA/repair pull request #25
Opened 2023-08-16 08:04 UTC by PauBForgeFlow

2023-08-21 06:53 UTC, BernatPForgeFlow requested changes

2023-08-21 06:53 UTC, BernatPForgeFlow commented on repair_reinvoice/hooks.py
> +    with api.Environment.manage():
Since Odoo 15.0, Environment.manage() is useless. Maybe better to delete the line.

2023-08-25 07:06 UTC, OriolMForgeFlow reviewed
I have been testing it on Runboat, and it doesn't seem to be working properly yet. 
I've created the Repair Order, confirmed it, started and finished it. I've created an Invoice, created a Reverse Invoice (both invoices with confirmed payment), and the option to create a new Invoice doesn't show up again.

![Screenshot from 2023-08-25 09-02-01](https://github.com/OCA/repair/assets/123451545/ce9301b2-ce27-452d-be09-dd14ea60cc67)

![Screenshot from 2023-08-25 09-02-19](https://github.com/OCA/repair/assets/123451545/5dabafb7-fc14-443a-bee2-a18eaf3ed606)

2023-08-25 07:06 UTC, OriolMForgeFlow commented on repair_reinvoice/readme/USAGE.rst
> +Follow the Odoo standard repair module flow. When an invoice related to a MO is reversed,
Follow the Odoo standard repair module flow. When an invoice related to a **RO** is reversed,

2023-08-25 13:44 UTC, OriolMForgeFlow approved these changes
Code & Functional Review, LGTM!

2023-09-13 10:32 UTC, mariadforgeflow approved these changes
LGTM!

2024-03-26 09:00 UTC, LoisRForgeFlow commented
/ocabot migration repair_reinvoice

2024-03-26 09:04 UTC, LoisRForgeFlow approved these changes
/ocabot merge nobump

2024-03-26 09:06 UTC, LoisRForgeFlow commented on repair_reinvoice/models/repair_order.py
> +        return
I just aborted the merge, you need to return the repair_dict here.

2024-04-08 07:56 UTC, LoisRForgeFlow commented
@PauBForgeFlow could you attend my last comment? Thanks!

2024-04-08 08:08 UTC, LoisRForgeFlow commented
Thanks!

/ocabot merge nobump

2024-04-08 08:12 UTC, merged